# Generated by Django 5.0.2 on 2024-12-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_userprofile_user_type'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop_name', models.CharField(max_length=50)),
                ('Crops_type', models.IntegerField(choices=[(1, 'Vegetables'), (2, 'Fruits'), (3, 'Grains'), (4, 'Spices')], null=True)),
                ('Quantity', models.FloatField()),
                ('Plant_Date', models.DateField(verbose_name='Planting Date')),
                ('Harvest_Date', models.DateField(verbose_name='Harvest Date')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='dashboard.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.TextField()),
                ('capacity', models.FloatField()),
                ('address', models.TextField(null=True)),
                ('owner_name', models.TextField()),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('crops', models.ManyToManyField(blank=True, related_name='storages', to='product.crops')),
                ('store_manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='authentication.userprofile')),
            ],
        ),
    ]
