# Generated by Django 5.0.2 on 2024-12-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('farm_name', models.CharField(editable=False, max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='product.crops')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.storage')),
            ],
        ),
    ]
