# Generated by Django 5.0.2 on 2024-12-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_storageitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='temperature',
        ),
    ]
