# Generated by Django 5.0.2 on 2024-12-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_storageitem_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField(default=0.0)),
                ('protein', models.FloatField(default=0.0)),
                ('carbohydrates', models.FloatField(default=0.0)),
                ('fats', models.FloatField(default=0.0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_data', to='product.product')),
            ],
        ),
    ]
