# Generated by Django 5.0.2 on 2024-12-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crops',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='product.crops'),
            preserve_default=False,
        ),
    ]
