# Generated by Django 5.0.2 on 2024-12-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('fm', 'Farm Manager'), ('n', 'Nutritionist'), ('d', 'Distributor'), ('qao', 'Quality Assurance Officer'), ('sm', 'Store Manager'), ('frm', 'Factory Manager')], max_length=3),
        ),
    ]
